### ISSUE TITLE
jQuery 3

### ISSUE THREAD

**Issue by joho1968** [nicolas-t/Chocolat#78] opened 2018-01-18 15:44 UTC
Is this supposed to work with jQuery 3? I get no errors and no action :) Looking at the demo, there's "slightly" more going on than just a HTML / JS lightbox, so I'm sure I've done something wrong :)

**Comment by mattbag** [comment] 2018-01-22 05:47
Works for me

**Comment by joho1968** [comment] 2018-01-22 06:56
Great. Do you have a simple working example?

**Comment by ntlaseca** [comment] 2018-05-29 21:08
I think I may be encountering a similar issue. Chocolat worked fine until I upgraded to jQuery 3. I haven't made any other changes.

**Comment by the21st** [comment] 2018-07-25 08:57
I see there's been a commit for using jQuery 3. @nicolas-t can you please make a new release containing this change?

**Comment by mattbag** [comment] 2018-07-25 09:06
https://codepen.io/mattbag/pen/NBgYGe

No issues with the basic, maybe some options?

**Comment by nicolas-t** [comment] 2018-07-25 09:08
Working well for me too.
I'm creating a new release right now.

**Comment by nicolas-t** [comment] 2018-07-25 09:14
There you go : https://github.com/nicolas-t/Chocolat/releases/tag/0.4.20

I'm closing.
If you have a reproductible issue related to jquery 3 feel free to reopen.

**Closed by nicolas-t** 2018-07-25 09:14 UTC
