### ISSUE TITLE
Transition when you switch between the images

### ISSUE THREAD

**Issue by babeuloula** [nicolas-t/Chocolat#82] opened 2018-02-25 13:50 UTC
Hello, 

Is it possible to have a transition when you switch between  the images in gallery mode ?

Thanks

**Comment by nicolas-t** [comment] 2018-08-25 09:54
Thanks, closing as it's a duplicate of https://github.com/nicolas-t/Chocolat/issues/81

**Closed by nicolas-t** 2018-08-25 09:54 UTC
Labels: duplicate
